/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yobennett.lambdaarchitectures.gallop.schema;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DataUnit extends org.apache.thrift.TUnion<DataUnit, DataUnit._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DataUnit");
  private static final org.apache.thrift.protocol.TField HORSE_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("horse_property", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField MONITOR_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("monitor_property", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField ACTIVITY_FIELD_DESC = new org.apache.thrift.protocol.TField("activity", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HORSE_PROPERTY((short)1, "horse_property"),
    MONITOR_PROPERTY((short)2, "monitor_property"),
    ACTIVITY((short)3, "activity");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HORSE_PROPERTY
          return HORSE_PROPERTY;
        case 2: // MONITOR_PROPERTY
          return MONITOR_PROPERTY;
        case 3: // ACTIVITY
          return ACTIVITY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HORSE_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("horse_property", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, HorseProperty.class)));
    tmpMap.put(_Fields.MONITOR_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("monitor_property", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MonitorProperty.class)));
    tmpMap.put(_Fields.ACTIVITY, new org.apache.thrift.meta_data.FieldMetaData("activity", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ActivityEdge.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DataUnit.class, metaDataMap);
  }

  public DataUnit() {
    super();
  }

  public DataUnit(_Fields setField, Object value) {
    super(setField, value);
  }

  public DataUnit(DataUnit other) {
    super(other);
  }
  public DataUnit deepCopy() {
    return new DataUnit(this);
  }

  public static DataUnit horse_property(HorseProperty value) {
    DataUnit x = new DataUnit();
    x.setHorse_property(value);
    return x;
  }

  public static DataUnit monitor_property(MonitorProperty value) {
    DataUnit x = new DataUnit();
    x.setMonitor_property(value);
    return x;
  }

  public static DataUnit activity(ActivityEdge value) {
    DataUnit x = new DataUnit();
    x.setActivity(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case HORSE_PROPERTY:
        if (value instanceof HorseProperty) {
          break;
        }
        throw new ClassCastException("Was expecting value of type HorseProperty for field 'horse_property', but got " + value.getClass().getSimpleName());
      case MONITOR_PROPERTY:
        if (value instanceof MonitorProperty) {
          break;
        }
        throw new ClassCastException("Was expecting value of type MonitorProperty for field 'monitor_property', but got " + value.getClass().getSimpleName());
      case ACTIVITY:
        if (value instanceof ActivityEdge) {
          break;
        }
        throw new ClassCastException("Was expecting value of type ActivityEdge for field 'activity', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case HORSE_PROPERTY:
          if (field.type == HORSE_PROPERTY_FIELD_DESC.type) {
            HorseProperty horse_property;
            horse_property = new HorseProperty();
            horse_property.read(iprot);
            return horse_property;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case MONITOR_PROPERTY:
          if (field.type == MONITOR_PROPERTY_FIELD_DESC.type) {
            MonitorProperty monitor_property;
            monitor_property = new MonitorProperty();
            monitor_property.read(iprot);
            return monitor_property;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case ACTIVITY:
          if (field.type == ACTIVITY_FIELD_DESC.type) {
            ActivityEdge activity;
            activity = new ActivityEdge();
            activity.read(iprot);
            return activity;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case HORSE_PROPERTY:
        HorseProperty horse_property = (HorseProperty)value_;
        horse_property.write(oprot);
        return;
      case MONITOR_PROPERTY:
        MonitorProperty monitor_property = (MonitorProperty)value_;
        monitor_property.write(oprot);
        return;
      case ACTIVITY:
        ActivityEdge activity = (ActivityEdge)value_;
        activity.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case HORSE_PROPERTY:
          HorseProperty horse_property;
          horse_property = new HorseProperty();
          horse_property.read(iprot);
          return horse_property;
        case MONITOR_PROPERTY:
          MonitorProperty monitor_property;
          monitor_property = new MonitorProperty();
          monitor_property.read(iprot);
          return monitor_property;
        case ACTIVITY:
          ActivityEdge activity;
          activity = new ActivityEdge();
          activity.read(iprot);
          return activity;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case HORSE_PROPERTY:
        HorseProperty horse_property = (HorseProperty)value_;
        horse_property.write(oprot);
        return;
      case MONITOR_PROPERTY:
        MonitorProperty monitor_property = (MonitorProperty)value_;
        monitor_property.write(oprot);
        return;
      case ACTIVITY:
        ActivityEdge activity = (ActivityEdge)value_;
        activity.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case HORSE_PROPERTY:
        return HORSE_PROPERTY_FIELD_DESC;
      case MONITOR_PROPERTY:
        return MONITOR_PROPERTY_FIELD_DESC;
      case ACTIVITY:
        return ACTIVITY_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public HorseProperty getHorse_property() {
    if (getSetField() == _Fields.HORSE_PROPERTY) {
      return (HorseProperty)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'horse_property' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setHorse_property(HorseProperty value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.HORSE_PROPERTY;
    value_ = value;
  }

  public MonitorProperty getMonitor_property() {
    if (getSetField() == _Fields.MONITOR_PROPERTY) {
      return (MonitorProperty)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'monitor_property' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setMonitor_property(MonitorProperty value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.MONITOR_PROPERTY;
    value_ = value;
  }

  public ActivityEdge getActivity() {
    if (getSetField() == _Fields.ACTIVITY) {
      return (ActivityEdge)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'activity' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setActivity(ActivityEdge value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.ACTIVITY;
    value_ = value;
  }

  public boolean isSetHorse_property() {
    return setField_ == _Fields.HORSE_PROPERTY;
  }


  public boolean isSetMonitor_property() {
    return setField_ == _Fields.MONITOR_PROPERTY;
  }


  public boolean isSetActivity() {
    return setField_ == _Fields.ACTIVITY;
  }


  public boolean equals(Object other) {
    if (other instanceof DataUnit) {
      return equals((DataUnit)other);
    } else {
      return false;
    }
  }

  public boolean equals(DataUnit other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(DataUnit other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  /**
   * If you'd like this to perform more respectably, use the hashcode generator option.
   */
  @Override
  public int hashCode() {
    return 0;
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
