/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yobennett.lambdaarchitectures.gallop.schema;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HorsePropertyValue extends org.apache.thrift.TUnion<HorsePropertyValue, HorsePropertyValue._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HorsePropertyValue");
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField WEIGHT_FIELD_DESC = new org.apache.thrift.protocol.TField("weight", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField GENDER_FIELD_DESC = new org.apache.thrift.protocol.TField("gender", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField BREED_FIELD_DESC = new org.apache.thrift.protocol.TField("breed", org.apache.thrift.protocol.TType.I32, (short)4);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    WEIGHT((short)2, "weight"),
    /**
     * 
     * @see GenderType
     */
    GENDER((short)3, "gender"),
    /**
     * 
     * @see BreedType
     */
    BREED((short)4, "breed");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // WEIGHT
          return WEIGHT;
        case 3: // GENDER
          return GENDER;
        case 4: // BREED
          return BREED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.WEIGHT, new org.apache.thrift.meta_data.FieldMetaData("weight", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.GENDER, new org.apache.thrift.meta_data.FieldMetaData("gender", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, GenderType.class)));
    tmpMap.put(_Fields.BREED, new org.apache.thrift.meta_data.FieldMetaData("breed", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, BreedType.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HorsePropertyValue.class, metaDataMap);
  }

  public HorsePropertyValue() {
    super();
  }

  public HorsePropertyValue(_Fields setField, Object value) {
    super(setField, value);
  }

  public HorsePropertyValue(HorsePropertyValue other) {
    super(other);
  }
  public HorsePropertyValue deepCopy() {
    return new HorsePropertyValue(this);
  }

  public static HorsePropertyValue name(String value) {
    HorsePropertyValue x = new HorsePropertyValue();
    x.setName(value);
    return x;
  }

  public static HorsePropertyValue weight(double value) {
    HorsePropertyValue x = new HorsePropertyValue();
    x.setWeight(value);
    return x;
  }

  public static HorsePropertyValue gender(GenderType value) {
    HorsePropertyValue x = new HorsePropertyValue();
    x.setGender(value);
    return x;
  }

  public static HorsePropertyValue breed(BreedType value) {
    HorsePropertyValue x = new HorsePropertyValue();
    x.setBreed(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case NAME:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'name', but got " + value.getClass().getSimpleName());
      case WEIGHT:
        if (value instanceof Double) {
          break;
        }
        throw new ClassCastException("Was expecting value of type Double for field 'weight', but got " + value.getClass().getSimpleName());
      case GENDER:
        if (value instanceof GenderType) {
          break;
        }
        throw new ClassCastException("Was expecting value of type GenderType for field 'gender', but got " + value.getClass().getSimpleName());
      case BREED:
        if (value instanceof BreedType) {
          break;
        }
        throw new ClassCastException("Was expecting value of type BreedType for field 'breed', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case NAME:
          if (field.type == NAME_FIELD_DESC.type) {
            String name;
            name = iprot.readString();
            return name;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case WEIGHT:
          if (field.type == WEIGHT_FIELD_DESC.type) {
            Double weight;
            weight = iprot.readDouble();
            return weight;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case GENDER:
          if (field.type == GENDER_FIELD_DESC.type) {
            GenderType gender;
            gender = GenderType.findByValue(iprot.readI32());
            return gender;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case BREED:
          if (field.type == BREED_FIELD_DESC.type) {
            BreedType breed;
            breed = BreedType.findByValue(iprot.readI32());
            return breed;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case NAME:
        String name = (String)value_;
        oprot.writeString(name);
        return;
      case WEIGHT:
        Double weight = (Double)value_;
        oprot.writeDouble(weight);
        return;
      case GENDER:
        GenderType gender = (GenderType)value_;
        oprot.writeI32(gender.getValue());
        return;
      case BREED:
        BreedType breed = (BreedType)value_;
        oprot.writeI32(breed.getValue());
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case NAME:
          String name;
          name = iprot.readString();
          return name;
        case WEIGHT:
          Double weight;
          weight = iprot.readDouble();
          return weight;
        case GENDER:
          GenderType gender;
          gender = GenderType.findByValue(iprot.readI32());
          return gender;
        case BREED:
          BreedType breed;
          breed = BreedType.findByValue(iprot.readI32());
          return breed;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case NAME:
        String name = (String)value_;
        oprot.writeString(name);
        return;
      case WEIGHT:
        Double weight = (Double)value_;
        oprot.writeDouble(weight);
        return;
      case GENDER:
        GenderType gender = (GenderType)value_;
        oprot.writeI32(gender.getValue());
        return;
      case BREED:
        BreedType breed = (BreedType)value_;
        oprot.writeI32(breed.getValue());
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case NAME:
        return NAME_FIELD_DESC;
      case WEIGHT:
        return WEIGHT_FIELD_DESC;
      case GENDER:
        return GENDER_FIELD_DESC;
      case BREED:
        return BREED_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public String getName() {
    if (getSetField() == _Fields.NAME) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'name' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setName(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.NAME;
    value_ = value;
  }

  public double getWeight() {
    if (getSetField() == _Fields.WEIGHT) {
      return (Double)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'weight' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setWeight(double value) {
    setField_ = _Fields.WEIGHT;
    value_ = value;
  }

  /**
   * 
   * @see GenderType
   */
  public GenderType getGender() {
    if (getSetField() == _Fields.GENDER) {
      return (GenderType)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'gender' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  /**
   * 
   * @see GenderType
   */
  public void setGender(GenderType value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.GENDER;
    value_ = value;
  }

  /**
   * 
   * @see BreedType
   */
  public BreedType getBreed() {
    if (getSetField() == _Fields.BREED) {
      return (BreedType)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'breed' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  /**
   * 
   * @see BreedType
   */
  public void setBreed(BreedType value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.BREED;
    value_ = value;
  }

  public boolean isSetName() {
    return setField_ == _Fields.NAME;
  }


  public boolean isSetWeight() {
    return setField_ == _Fields.WEIGHT;
  }


  public boolean isSetGender() {
    return setField_ == _Fields.GENDER;
  }


  public boolean isSetBreed() {
    return setField_ == _Fields.BREED;
  }


  public boolean equals(Object other) {
    if (other instanceof HorsePropertyValue) {
      return equals((HorsePropertyValue)other);
    } else {
      return false;
    }
  }

  public boolean equals(HorsePropertyValue other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(HorsePropertyValue other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  /**
   * If you'd like this to perform more respectably, use the hashcode generator option.
   */
  @Override
  public int hashCode() {
    return 0;
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
