/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yobennett.lambdaarchitectures.gallop.schema;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MonitorType implements org.apache.thrift.TEnum {
  ACTIVITY(1);

  private final int value;

  private MonitorType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MonitorType findByValue(int value) { 
    switch (value) {
      case 1:
        return ACTIVITY;
      default:
        return null;
    }
  }
}
